### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by cartant** [johnlindquist/react-streams#1]
What is your preferred way of dealing with and maintaining TypeScript type declarations? Would you be open to a PR that adds a `.d.ts` file? Or would you prefer types to be managed using [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by johnlindquist** [comment]
Happy to accept a d.ts. I'd even like to dev in TypeScript, but @types/react wasn't up-to-date for v16.3 when I started

**Comment by cartant** [comment]
> I'd even like to dev in TypeScript ...

Cool. I'll have a look at how the current build works and will look at what'd be needed to go "full TypeScript."

**Comment by johnlindquist** [comment]
> "current build"...
`tsc` with "allowJS" enabled 😝

**Comment by cartant** [comment]
I've added type declarations - see [this branch](https://github.com/cartant/react-streams/tree/add-types) - but I see that the API has changed. I'm not sure that `switchProps` can be typed. I will have another look, later.

**Comment by johnlindquist** [comment]
The api should be simpler now for `pipeProps`. I simply check which exists (children/render/nothing) and use that rather than having 3 separate functions.

`switchProps` came from typing
```
pluck("foo"),
switchMap(foo => stream$.pipe(startWith(foo)))
```
too often. So `switchProps` is just a wrapper around that (I updated the examples on the README.md to show it in action)

**Comment by cartant** [comment]
Yeah, it's certainly simpler. I've opened a PR with the declarations for the new API. And `switchProps` was less of a problem than I thought it would be.
