### ISSUE TITLE
Need to reduce the file package size

### ISSUE THREAD

**Issue by leihuang69** [johnlindquist/react-streams#11]
This package is too big. Import cost tells me that it takes 122.3k just to import 4 functions.
![screen shot 2018-06-08 at 5 18 04 pm](https://user-images.githubusercontent.com/24438174/41150169-fc33048c-6b3f-11e8-8f1f-0ffdb099ae48.png)

**Comment by johnlindquist** [comment]
@leihuang69 I did an initial pass at migrating to rollup. I'll work on further optimizations soon. Thanks for the bump :)

![image](https://user-images.githubusercontent.com/36073/41161153-0df6b836-6aef-11e8-97b8-73e6b039ec50.png)
