### ISSUE TITLE
Subject shared between component instances

### ISSUE THREAD

**Issue by cartant** [johnlindquist/react-streams#4]
I don't believe the change made in https://github.com/johnlindquist/react-streams/commit/258dc0e5707700c887589eb8966cdf484c0fea94 is safe.

Using [a `Subject` instance](https://github.com/johnlindquist/react-streams/blob/291db5624286cace6a4573fe666a53c0e74607ec/src/index.js#L7) that's created outside of the `Component` and calling it from within [`getDerivedStateFromProps `](https://github.com/johnlindquist/react-streams/blob/291db5624286cace6a4573fe666a53c0e74607ec/src/index.js#L23-L26) means that the subject is shared between all instances of the component. So each component instance will be notified of its props and of every other component instance's props.

**Comment by johnlindquist** [comment]
@cartant oh yeah, duh 🤪. I was too busy thinking about how to get rid of `UNSAFE_`. Hmm... Any ideas?

**Comment by cartant** [comment]
I'm still digesting [this blog post](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) of Brian Vaughn's.

And I've been looking at the implementation of the React [create-subscription API](https://github.com/facebook/react/blob/v16.3.1/packages/create-subscription/src/createSubscription.js).

And I've discovered that the [`recompose` implementation](https://github.com/acdlite/recompose/blob/v0.26.0/src/packages/recompose/componentFromStream.js#L32-L57) has problems because it pairs `componentWillMount` with `componentWillUnmount`.

Unfortunately, today, I don't have the time to have a good think about this stuff. (Too many boring administrative tasks that I've put off for far too long.)

For the moment, I'd be inclined to revert to your initial implementation that used `UNSAFE_componentWillReceiveProps`.

**Comment by johnlindquist** [comment]
I'm DM'ing Brian on twitter about making sure this is async safe right now :)

**Comment by johnlindquist** [comment]
@cartant After chatting with Brian, we landed on:

https://github.com/johnlindquist/react-streams/blob/master/src/index.js#L21

1. `distinctUntilChanged` is extremely important, otherwise it falls `setState` + `componentDidUpdate` recurses
2. We grab `this.props` off the component, not the `prevProps` arg from `componentDidUpdate`

This seems to be holding solid and "async safe".
